In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
b = [5,6,7,8]
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
[a[i] + b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [4]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr[1:3,1:3]    ## start_row:end_row,start_col:end_column

array([[5, 6],
       [8, 9]])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [9]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a = np.arange(10)

In [12]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [16]:
### VECTOR OPERATION

In [17]:
a = np.array([1,2,3])
a+2

array([3, 4, 5])

In [18]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [19]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [20]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
np.linalg.inv(arr)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [23]:
np.linalg.det(arr)

np.float64(-9.51619735392994e-16)

In [24]:
arr = np.resize(a,(3,4))

In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.sum(a,axis=0)

array([12, 15, 18])

In [31]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [32]:
def mean(array):
    n=len(array)
    return np.sum(array)/n

In [33]:
mean(np.array([1,2,3,4,5,6]))

np.float64(3.5)

In [40]:
def variance(array):
    n = len(array)
    m = mean(array)
    return np.sum((array - m)**2) / n

In [41]:
variance(np.array([1,2,3,4,5,6]))

np.float64(2.9166666666666665)

In [46]:
def min_max(array):
    minimum = np.min(array)
    maximum = np.max(array)
    return minimum,maximum

In [47]:
min_max(np.array([1,2,3,4,5,6]))

(np.int64(1), np.int64(6))

In [54]:
def std_dev(array):
    return np.sqrt(variance(array))

In [55]:
def std_scalar(array):
    m = mean(array)
    s = std_dev(array)

    return (array - m) / s

In [56]:
std_scalar(np.array([1,2,3,4,5,6]))

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])